source=~/.config/mango/autostart
source=~/.config/mango/envs
source=~/.config/mango/settings
source=~/.config/mango/binds
source=~/.config/mango/monitors
source=~/.config/mango/layouts
source=~/.config/mango/visuals
source=~/.config/mango/rules
source=~/.config/mango/theme
